#!/bin/bash
# Initialize storage directories for multi-zone route management

set -e

echo "========================================="
echo "Multi-Zone Route Management Setup"
echo "========================================="

# Create routes directory (zones directory should already exist)
mkdir -p routes
echo "✓ Created routes/ directory"

# Create README in routes directory
cat > routes/README.md << 'EOF'
# Routes Directory

This directory stores transit routes between mowing zones.

## File Format

Routes are stored as YAML files with the following structure:

```yaml
route_id: "route_001_backyard_to_frontyard"
route_name: "Driveway Route"
from_zone_id: "backyard"
to_zone_id: "frontyard"
route_type: "DRIVEWAY"  # DRIVEWAY, GATE_PASSAGE, AROUND_BUILDING, NARROW_PATH, ROAD_CROSSING
bidirectional: true
max_speed_mps: 0.5
path_width_meters: 2.0
mow_during_transit: false
tags: ["paved", "main"]
created_at: "2024-01-15T10:30:00Z"
waypoints:
  - latitude: 37.12345
    longitude: -122.12345
    altitude: 10.5
  - latitude: 37.12346
    longitude: -122.12346
    altitude: 10.6
total_distance_meters: 15.3
estimated_transit_time_seconds: 30.6
```

## Route Types

- **DRIVEWAY**: Wide paved routes, typically between front and back yards
- **GATE_PASSAGE**: Narrow passages through gates or fences
- **AROUND_BUILDING**: Routes that go around structures
- **NARROW_PATH**: Constrained paths with limited maneuvering room
- **ROAD_CROSSING**: Routes that cross roads or driveways (use caution)

## Best Practices

1. **GPS Quality**: Only record routes with HDOP < 2.0
2. **Speed**: Walk slowly and steadily along the desired path
3. **Weather**: Record in clear weather for best GPS accuracy
4. **Buffer**: Account for 1-2 meter GPS drift in path width
5. **Bidirectional**: Most routes should be bidirectional unless one-way required
6. **Mowing**: Typically set `mow_during_transit: false` for transit routes

## File Naming

Files are automatically named: `{from_zone}_to_{to_zone}_{timestamp}.yaml`

Example: `backyard_to_frontyard_1705330200.yaml`
EOF

echo "✓ Created routes/README.md"

# Ensure zones directory exists
mkdir -p zones
echo "✓ Verified zones/ directory exists"

# Create example zone graph file
cat > routes/.zone_graph_example.yaml << 'EOF'
# Example Zone Graph (auto-generated by zone_manager)
# This file shows the connectivity between zones based on available routes

nodes:
  - zone_id: backyard
    zone_name: "Back Yard"
    center_lat: 37.12345
    center_lon: -122.12345
    priority: 5
    estimated_mow_time_seconds: 600
    
  - zone_id: frontyard
    zone_name: "Front Yard"
    center_lat: 37.12350
    center_lon: -122.12350
    priority: 3
    estimated_mow_time_seconds: 450

edges:
  - from_zone_id: backyard
    to_zone_id: frontyard
    route_id: route_001_backyard_to_frontyard
    distance_meters: 25.5
    transit_time_seconds: 51.0
    bidirectional: true
EOF

echo "✓ Created example zone graph"

echo ""
echo "========================================="
echo "Setup Complete!"
echo "========================================="
echo ""
echo "Directory structure:"
echo "  zones/       - Zone definitions"
echo "  routes/      - Transit routes between zones"
echo ""
echo "Next steps:"
echo "  1. Define zones using the Zone Recorder"
echo "  2. Record transit routes using Route Manager"
echo "  3. View zone graph and connectivity"
echo ""
