gps_node:
  ros__parameters:
    # Serial port configuration
    # For Jetson Orin Nano - GPS HAT on GPIO UART
    serial_port: '/dev/ttyTHS1'
    
    # LC29H default baud rate
    baud_rate: 115200
    
    # Frame ID for TF
    frame_id: 'gps'
    
    # Publishing rate in Hz
    publish_rate: 10.0
    
    # Enable RTK mode (requires RTK-capable GPS module and base station)
    use_rtk: false
    
    # NTRIP configuration for RTK corrections
   # ntrip_server: '63.133.235.92'
    ntrip_port: 2101
    ntrip_mountpoint: 'BASE'
    ntrip_username: 'nfazio'
    ntrip_password: '123456789'
    ntrip_server: '10.0.212.119'
